### ISSUE TITLE
ezt.py doesn't work with Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gstein/ezt#5]
```
ezt.py doesn't work with Python 3.
The attached patch fixes this problem.
```

Original issue reported on code.google.com by `Arfrever...@gmail.com` on 10 May 2009 at 1:59

Attachments:
- [ezt.py.patch](https://storage.googleapis.com/google-code-attachments/ezt/issue-5/comment-0/ezt.py.patch)

**Comment by gstein** [comment]
Fixed!
